language: python

python:
  - "3.6"

script:
  - cd test/ && behave
  - cd ..
  # Run py.test with 'v' (verbose) to show test function names and
  # 'rs' to show reasons for skipped tests
  - pytest -v -rs
